version: 2.1

# Define the jobs we want to run for this project
jobs:
  verify:
    working_directory: ~/temp
    docker:
      - image: circleci/node:current
    steps:
      - checkout
      - run: npm i
      - run: npm test

